### ISSUE TITLE
No releases since April?

### ISSUE THREAD

**Issue by jutley** [cloudhut/kminion#130]
I just found this project and it seems extremely valuable for my use case. In particular, I'd like to use the endToEnd testing to measure client-side latencies.

It looks like there hasn't been any releases since April, and the latest release does not have the features I would like to use. Are there any plans to create a new release anytime soon? I can consider using a non-stable build, though this is typically not a good idea.

**Comment by weeco** [comment]
Hey @jutley ,
I'm glad KMinion helps you with your work. It's right that the last release has been created long time ago. The biggest change since then is definetely the addition of the e2e feature. I'm not entirely convinced yet that this feature works exactly the way it is supposed to, because I had some issues during rolling broker updates / restarts, but generally I think you can use a docker image that is built against master.

The main purpose of that feature was to have some end to end testing of a Kafka cluster for the purpose of measuring SLA/SLOs. Therefore it is somewhat crtical that KMinion properly handles broker restarts / leader reelections because we don't want to get paged if the cluster is still fine. But if you are primarily interested in latencies I think you can already rely on KMinion:

![image](https://user-images.githubusercontent.com/23424570/141643159-dd8b992b-555c-4abf-a023-bf2e35fcaa0d.png)

**Comment by jutley** [comment]
Thanks for the clarification! I'll do some testing to determine whether the current state is good enough for our needs.

**Comment by jutley** [comment]
For what it's worth, we've been running kminion during some rolling restarts and broker replacements, and the kminion pods have been connecting to all Kafka brokers correctly along the way.
