### ISSUE TITLE
Unreliable lag metrics?

### ISSUE THREAD

**Issue by ZVilusinsky** [cloudhut/kminion#27]
Hi, we've been successfully using minion since first stable, but recently a task from our bigdata buys was sent my way, that lag metrics seem not to reflect real state. While data on the actual server show a regular lag 20ish per partition, resulting topic and partition lag metric is happily showing zero lag.
![topiclag1](https://user-images.githubusercontent.com/47591967/72805791-fc3c8c00-3c53-11ea-9423-e7ed0b66ae48.png)
![topiclag2](https://user-images.githubusercontent.com/47591967/72805790-fc3c8c00-3c53-11ea-93e3-fc0467ab3bdb.png)

Any thoughts on this behaviour? I our other usecases (say 2 mesages / second in topic) it seems to work fine, but here with a high throughput, it reports zero most of the time and then sometimes shows some lag. Kafka version used on their server is something <1.0 as far as I know.

**Comment by weeco** [comment]
Hey,
that's probably due to the way Kafka Minion works. It periodically fetches the partition offset (high water mark) from the cluster and continously gets a stream of committed offsets from the consumers. Thus one can say the consumer offsets are more recent than the water marks (because they are pulled every 5s by default, see: https://github.com/cloudworkz/kafka-minion/blob/master/kafka/cluster.go#L117). 

It's not uncommon that a consumer group would report that it has consumed offset 100, while the cluster module was reported the high water mark for the same partition is 98. Then the exporter would export reports a lag of 0.

The difference is: The shell script you ran above fetches the offsets (watermark and group offsets) as you execute it, while Kafka minion maintains the cached values for watermarks for up to 5 seconds.

Does that make sense?

**Comment by lcir** [comment]
Hi ,

i have question. Imagine example from graph from Zdenek. Consumer lag in this case was 1/13 almost the same as 1/14. But Minion reports information about lag from cca 1/13 8:00 PM.

It's OK? Why Minion report in the same traffic and with the same consumer lag one day, but another no?

**Comment by weeco** [comment]
@lcir I am not sure if I understood your question.

OP seem to be rather surprised that the lag in Kafka Minion is reported as 0 (instead of the expected 20 here and there as reported by the shell scripts).

**Comment by lcir** [comment]
@weeco i'm the BigData guy which @ZVilusinsky mentioned in his question. 

We try to understand Minons behavior. Why Minion report zero lag one day  and another day non-zero lag? When the traffic in Kafka topic is the same. Consumer information from server client is non-zero, but Minion still report zero lag for many hours?

**Comment by weeco** [comment]
- Maybe you can check the logs and see whether kafka minion has/had troubles fetching the watermarks from this topic/partitions?
- Maybe the throughput during that timeframe was actually higher than usual / or the consumer group during that time was actually slower than usual?
- Another potential reason could be frequent rebalances?
- Very unlikely but still to be considered: Was Kafka Minion able to keep up with the throughput of the `__consumer_offsets` topic (see internal panels on the Grafana dashboard)

There are many reasons why the lag during that day could be higher than usual. If you don't trust the reported lags it probably makes sense to use another prometheus exporter for kafka lags and leave it running side by side and compare that in Grafana.
