### ISSUE TITLE
Can't run two charts under the same Prometheus

### ISSUE THREAD

**Issue by Cho1409** [cloudhut/kminion#43]
Hi guys,

I'm having an issue that I can't run two or more kafka-minion charts under the same Prometheus. The problem is that Prometheus is warning me _Out of Order samples_:

`level=debug ts=2020-05-30T03:17:35.039Z caller=scrape.go:1245 component="scrape manager" scrape_pool=exporters/kafka-prod-kafka-minion/0 target=http://99.99.99.99:8080/metrics msg="Out of order sample" series="kafka_minion_topic_partition_message_count{partition=\"9\",topic=\"kafka-minion-output-dev-prod\"}"
level=debug ts=2020-05-30T03:17:35.039Z caller=scrape.go:1245 component="scrape manager" scrape_pool=exporters/kafka-prod-kafka-minion/0 target=http://99.99.99.99:8080/metrics msg="Out of order sample" series="kafka_minion_topic_partition_message_count{partition=\"9\",topic=\"kafka-minion-output-dev-qa\"}"`

Is there anything that I need to define on my chart before deploying a second kafka-minion under my Prometheus?

Note: Just ignore the IP stuff.

**Comment by weeco** [comment]
Each Prometheus target being scraped needs to have an unique label (e.g. pod id + container name if you are on Kubernetes). Otherwise you'll end up with with multiple metrics from different sources for the exact same metric name.

As this is related to Prometheus but not to KMinion I'll close this issue.
