### ISSUE TITLE
kafka_minion_topic_partition_message_count

### ISSUE THREAD

**Issue by PLarboulette** [cloudhut/kminion#72]
Hello, 

In the last version, kafka_minion_topic_partition_message_count has disappear; 

Do you intend to restore it? Or do you have a suggestion to replace it?

Thanks

**Comment by weeco** [comment]
Hey @PLarboulette ,
I'm not entirely sure whether I want to restore it. What it did was just partition high watermark - partition low watermark. These two metrics are still exposed, so that you could rebuild this behaviour. Message count is slightly missleading because it doesn't reflect the actual message count in compacted topics.

I hope that helps for now. I still have to document the exposed metrics and I'll also create a new dashboard that uses the existing metrics then I'll likely see whether that makes sense or not. In general I try to avoid metrics - especially those where a series for each partition is required - in order to reduce the number of exposed metric serieses on Kafka clusters with many thousand partitions.

**Comment by PLarboulette** [comment]
Hello, 

Thank you for your answer, we should be able to get away with this :) 

And yes, I completely agree on the exposure of metrics, if we can, as much as stay as light as possible !

**Comment by weeco** [comment]
Here's the overview of all exported metrics. To calculate the number of max messages you can use the low and high water mark sum that already sums all the high + low mark offsets across all partitions in a topic:

```
kminion_kafka_topic_high_water_mark_sum{topic_name="__consumer_offsets"} 1.512023846873e+12
kminion_kafka_topic_low_water_mark_sum{topic_name="__consumer_offsets"} 0
```
